server:
  port: 80

jasypt:
  encryptor:
    password: BdaObXaELAA

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/school?characterEncoding=utf8
    username: ENC(Y7UdakGg4LkVXRW70EwmGA==)
    password: ENC(T6TOAJujjs6oBX8Z3EeomTrpnI4/e8Mp)


  thymeleaf:
    cache: false



